### ISSUE TITLE
[Talk] 議程組內部審稿 一階審稿 : 稿件審稿&回覆紀錄

### ISSUE THREAD

**Issue by Xiao75896453** [pycontw/pycontw-program-2024#109]
### What problem does this task solve?

依據一階審稿結果與投稿者回覆，記錄投稿者投稿結果狀態

### What does the proposed task look like?
透過 google sheet 紀錄

投稿結果狀態
- 錄取 + 願意參加
- 錄取 + 不願意參加
- 未錄取
- 審稿中

**Comment by kazanTW** [comment]
我可以協助這份工作

**Comment by Xiao75896453** [comment]
> 我可以協助這份工作

To @kazanTW 
感謝 Kazan 願意幫忙 🙏🙏
不過這個 issue 會使用已經統計好的 csv 直接完成
並交由後續協助聯絡投稿者的志工完成相關投稿結果紀錄

因此暫時不須額外協助，很謝謝 Kazan ~

[Discord 討論串](https://discord.com/channels/752904426057892052/1236319887874461778)

**Comment by Xiao75896453** [comment]
Thanks @oliviawang0615 for completing this task 🤗
