### ISSUE TITLE
[Talk] 一階審稿 : 催審稿委員審稿信件 - 最後一封

### ISSUE THREAD

**Issue by andylee830914** [pycontw/pycontw-program-2024#15]
### What problem does this feature solve?

提審催促審稿委員進行一階審稿

### What does the proposed feature look like?

信件內容大致包含
1. 提醒 第一階段審稿結束時間 + 最後幾天
2. 感謝
3. PyCon TW 2024 連結

[信件參考](https://hackmd.io/n_zikJ7rQRCTojlMdnXoxA?view#20230420-%E7%AC%AC%E4%B8%80%E9%9A%8E%E6%AE%B5%E5%82%AC%E5%AF%A9%E7%A8%BF%E8%80%85---%E7%AC%AC%E4%B8%89%E5%B0%81)
[寄信指南](https://hackmd.io/Qcv4BAFzRe2io8xitiUKsg?view#%E5%AF%84%E4%BF%A1)

**Comment by ma9ikarp** [comment]
已完成
