### ISSUE TITLE
[Talk] 議程組內部審稿 一階審稿 : 通知投稿者錄取信件

### ISSUE THREAD

**Issue by andylee830914** [pycontw/pycontw-program-2024#17]
### What problem does this feature solve?

依據一階審稿結果，通知投稿者一階審稿直接錄取
並依據投稿者回覆，紀錄出席意願

### What does the proposed feature look like?
⚠信件需要客製化寄出 ⚠
因每位投稿者可能投多篇稿件 
因此信件內容須包含稿件名稱等資訊

- 錄取結果
- 感謝
- 詢問意願
- 購票資訊
- 財務補助

若投稿者回信問題無法處理，可詢問組長協助處理

### Reference
[信件參考](https://hackmd.io/x1deCjfZTV-Svwu-HtN41w#20230426-%E7%AC%AC%E4%B8%80%E9%9A%8E%E6%AE%B5%E9%8C%84%E5%8F%96%E4%BF%A1)

**Comment by Xiao75896453** [comment]
@oliviawang0615 Congregations on completing this task 🥳
