### ISSUE TITLE
[Talk] 議程組內部審稿 一階審稿 : 提醒投稿者回覆錄取信件

### ISSUE THREAD

**Issue by andylee830914** [pycontw/pycontw-program-2024#19]
### What problem does this feature solve?

提醒尚未回覆的一階審稿直接錄取投稿者，回覆先前寄出的錄取通知
並依據投稿者回覆，紀錄出席意願

### What does the proposed feature look like?

信件內容包含不限於
- 錄取結果
- 前一封信件資訊
- 回覆期限
- 意願詢問

若投稿者回信問題無法處理，可詢問組長協助處理

### Reference
[信件參考](https://hackmd.io/x1deCjfZTV-Svwu-HtN41w?view#20230506-%E6%8F%90%E9%86%92%E8%AC%9B%E8%80%85%E5%9B%9E%E8%A6%86%E9%8C%84%E5%8F%96%E7%9A%84%E4%BF%A1%E4%BB%B6)

**Comment by Xiao75896453** [comment]
@oliviawang0615 Congregations on completing this task 😊
