### ISSUE TITLE
[Talk] 投稿者修改稿件 : 提醒投稿者修訂稿件期限信件

### ISSUE THREAD

**Issue by andylee830914** [pycontw/pycontw-program-2024#20]
### What problem does this feature solve?

提醒投稿者修訂稿件期限

### What does the proposed feature look like?

信件內容包含不限於以下
- 稿件修改時程
- 審稿流程

### Reference

- [信件參考](https://hackmd.io/x1deCjfZTV-Svwu-HtN41w#20230509-%E7%AC%AC%E4%BA%8C%E9%9A%8E%E6%AE%B5%E4%BF%AE%E8%A8%82%E7%A8%BF%E4%BB%B6%E6%9C%9F%E9%99%90%E6%8F%90%E9%86%92)

**Comment by Xiao75896453** [comment]
@ma9ikarp Congregations on completing this task 🎉
