### ISSUE TITLE
[Talk] 二階審稿 : 提醒審稿委員開始二階審稿信件

### ISSUE THREAD

**Issue by andylee830914** [pycontw/pycontw-program-2024#23]
### What problem does this feature solve?

提醒審稿委員二階審稿開始以及二階審稿資訊

### What does the proposed feature look like?

信件內容包含不限於
- 感謝審稿委員
- 二階審稿時間
- 審稿指南、審稿系統連結

### Reference
[信件參考](https://hackmd.io/n_zikJ7rQRCTojlMdnXoxA#20230517-%E7%AC%AC%E4%BA%8C%E9%9A%8E%E6%AE%B5-%E5%AF%A9%E7%A8%BF%E9%96%8B%E5%A7%8B%E9%80%9A%E7%9F%A5)

**Comment by Xiao75896453** [comment]
@lu791019 Congregations on completing this task 👍
