### ISSUE TITLE
[Talk] 二階審稿 : 催審稿委員審稿信件 - 第一封

### ISSUE THREAD

**Issue by andylee830914** [pycontw/pycontw-program-2024#24]
### What problem does this feature solve?

提審催促審稿委員進行二階審稿

### What does the proposed feature look like?
因今年僅寄兩封審稿通知信件，因此將去年審稿通知第一封與第二封內容合併

信件內容包含不限於
- 二階審稿時間
- 二階審稿方式
- 錄取稿件公布時間 6/10
- 請求審稿協助
- 審稿系統連結
- 感謝審稿委員

### Reference
[信件參考 1](https://hackmd.io/n_zikJ7rQRCTojlMdnXoxA#20230523-%E7%AC%AC%E4%BA%8C%E9%9A%8E%E6%AE%B5-%E5%AF%A9%E7%A8%BF%E9%80%9A%E7%9F%A5---%E7%AC%AC%E4%B8%80%E5%B0%81)
[信件參考 2](https://hackmd.io/n_zikJ7rQRCTojlMdnXoxA#20230530-%E7%AC%AC%E4%BA%8C%E9%9A%8E%E6%AE%B5-%E5%AF%A9%E7%A8%BF%E9%80%9A%E7%9F%A5---%E7%AC%AC%E4%BA%8C%E5%B0%81)

**Comment by ma9ikarp** [comment]
[https://hackmd.io/wEHeigrFRYan1A_e95SPBQ#20240526-第二階段催稿通知](https://hackmd.io/wEHeigrFRYan1A_e95SPBQ#20240526-第二階段催稿通知)

**Comment by Xiao75896453** [comment]
Thanks to @ma9ikarp for completing this issue and providing the relational hyperlink. 🤩
