### ISSUE TITLE
[Talk] 二階審稿 : 催審稿委員審稿信件 - 最後一封

### ISSUE THREAD

**Issue by andylee830914** [pycontw/pycontw-program-2024#26]
### What problem does this feature solve?

提審催促審稿委員進行二階審稿

### What does the proposed feature look like?

信件內容包含不限於
- 二階審稿時間
- 錄取稿件公布時間 6/10
- 請求審稿協助
- 審稿系統連結
- 感謝審稿委員

### Reference
[信件參考](https://hackmd.io/n_zikJ7rQRCTojlMdnXoxA?view#20230602-%E7%AC%AC%E4%BA%8C%E9%9A%8E%E6%AE%B5-%E5%AF%A9%E7%A8%BF%E9%80%9A%E7%9F%A5---%E7%AC%AC%E4%B8%89%E5%B0%81)

**Comment by Xiao75896453** [comment]
@oliviawang0615 @ma9ikarp Congregations on completing this task ~ 🐈
