### ISSUE TITLE
[Talk] 議程組內部審稿 二階審稿 : 確認審稿意見符合 CoC

### ISSUE THREAD

**Issue by andylee830914** [pycontw/pycontw-program-2024#28]
### What problem does this feature solve?

確認審稿意見符合 CoC 

### What does the proposed feature look like?

1. 輸出審稿意見
2. 檢查並記錄審稿意見是否符合 CoC
3. 請 網頁組 協助設定 審稿意見全部開放
4. 議程組 將不符 CoC 審稿意見關閉

### Reference

- [審稿指南](https://pycontw.github.io/reviewer-guidebook/)
- [CoC](https://tw.pycon.org/2024/zh-hant/about/code-of-conduct)

**Comment by Xiao75896453** [comment]
This Issue has been completed 🥳
[Discord Discussion Record](https://discord.com/channels/752904426057892052/1233456592649850881)
