### ISSUE TITLE
[Talk] 感謝審稿委員 : 感謝各位審稿者信件

### ISSUE THREAD

**Issue by andylee830914** [pycontw/pycontw-program-2024#31]
### What problem does this feature solve?

感謝審稿者協助審稿

### What does the proposed feature look like?

信件內容包含不限於
- 感謝審稿委員
- 審稿結束
- 本屆 PyCon 資訊
- 優惠票資訊

### Reference
[信件參考](https://hackmd.io/n_zikJ7rQRCTojlMdnXoxA?view#20230614-%E6%84%9F%E8%AC%9D%E5%90%84%E4%BD%8D%E5%AF%A9%E7%A8%BF%E8%80%85)

**Comment by Xiao75896453** [comment]
Thanks @andylee830914 @tlyu0419 for completing this issue 😊
