### ISSUE TITLE
[Talk] Talk 2024 規劃

### ISSUE THREAD

**Issue by andylee830914** [pycontw/pycontw-program-2024#4]
- 邀稿
   -  投放範圍：過去講者、國際 PyCon 
   -  時程：
- CFP時程
   -  投稿：
   -  一階審稿：
   -  修改稿件：
   -  二階審稿：
   -  公告正備取名單：
- 大會
   - R0、 R1、R2：一般演講
   - R3：
      - Day1：社群軌（邀稿、社群推薦）
      - Day2：Tutorial

**Comment by Xiao75896453** [comment]
[Talk 組文件](https://hackmd.io/Qcv4BAFzRe2io8xitiUKsg)

**Comment by Xiao75896453** [comment]
待討論草稿

第二階段審稿通知 兩個 issue 一樣
https://github.com/pycontw/pycontw-program-2024/issues/23
https://github.com/pycontw/pycontw-program-2024/issues/24

感謝/通知信 是最後嗎
https://github.com/pycontw/pycontw-program-2024/issues/9
https://github.com/pycontw/pycontw-program-2024/issues/12
https://github.com/pycontw/pycontw-program-2024/issues/31

這是什麼
https://github.com/pycontw/pycontw-program-2024/issues/19
https://github.com/pycontw/pycontw-program-2024/issues/30

議程編排 時間
https://github.com/pycontw/pycontw-program-2024/issues/29

Project 通知
Issue 格式
Gantt
Personal

行銷貼文
mail handler

資料管理

reviewer
pr
