### ISSUE TITLE
[Talk[ 一階審稿 : 提醒審稿委員開始一階審稿信件

### ISSUE THREAD

**Issue by Xiao75896453** [pycontw/pycontw-program-2024#65]
### What problem does this feature solve?

提醒審稿委員開始一階審稿

### What does the proposed feature look like?

於 2024/4/9 (一階審稿開始日) 寄出給今年審稿委員

信件內容大致包含
1. 提醒 第一階段審稿
2. 確認 投稿系統帳號審稿權限
3. 感謝

[信件參考](https://hackmd.io/n_zikJ7rQRCTojlMdnXoxA#20230401-%E5%AF%A9%E7%A8%BF%E5%A7%94%E5%93%A1%E6%84%9F%E8%AC%9D%E9%80%9A%E7%9F%A5%E4%BF%A1)

**Comment by ma9ikarp** [comment]
done
