### ISSUE TITLE
[Talk] Call for Proposals : 聯絡曾經投稿者邀請投稿信件

### ISSUE THREAD

**Issue by Xiao75896453** [pycontw/pycontw-program-2024#81]
### What problem does this feature solve?
主動推近年投稿者投稿

### What does the proposed feature look like?
寄信給近年投稿者

[信件參考](https://hackmd.io/x1deCjfZTV-Svwu-HtN41w) (去年似乎沒有寫過)

**Comment by andylee830914** [comment]
@LoisChen68 參考一下這個 ticket
